#############################################################################
# Makefile for building: .\assignment.js
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  ..\build-76\assignment76.pro
# Template: app
# Command: D:\Software\Qt\5.15.2\wasm_32\bin\qmake.exe -o Makefile ..\build-76\assignment76.pro -spec wasm-emscripten "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = emcc
CXX           = em++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -g -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -g -std=gnu++11 -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra $(DEFINES)
INCPATH       = -I..\build-76 -I. -ID:\Software\Qt\5.15.2\wasm_32\include -ID:\Software\Qt\5.15.2\wasm_32\include\QtWidgets -ID:\Software\Qt\5.15.2\wasm_32\include\QtGui -ID:\Software\Qt\5.15.2\wasm_32\include\QtCore -I. -I. -I/.emscripten_ports/openssl/include -ID:\Software\Qt\5.15.2\wasm_32\mkspecs\wasm-emscripten
QMAKE         = D:\Software\Qt\5.15.2\wasm_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Software\Qt\5.15.2\wasm_32\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Software\Qt\5.15.2\wasm_32\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
TAR           = 
COMPRESS      = 
DISTNAME      = assignment.js1.0.0
DISTDIR = E:\jucse\gitRepo\BCSE-III\graphicsLab\build-assignment76-Qt_5_15_2_WebAssembly-Debug\.tmp\assignment.js1.0.0
LINK          = em++
LFLAGS        = -s WASM=1 -s FULL_ES2=1 -s FULL_ES3=1 -s USE_WEBGL2=1 -s EXIT_RUNTIME=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s EXTRA_EXPORTED_RUNTIME_METHODS=["UTF16ToString","stringToUTF16"] --bind -s FETCH=1 -g4 -s WASM=1 -s FULL_ES2=1 -s FULL_ES3=1 -s USE_WEBGL2=1 -s EXIT_RUNTIME=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s EXTRA_EXPORTED_RUNTIME_METHODS=["UTF16ToString","stringToUTF16"] --bind -s FETCH=1 -s ASSERTIONS=2 -s DEMANGLE_SUPPORT=1 -s GL_DEBUG=1 --profiling-funcs -s ALLOW_MEMORY_GROWTH=1 --source-map-base http://localhost:8000/
LIBS          = $(SUBLIBS) D:/Software/Qt/5.15.2/wasm_32/plugins/platforms/libqwasm.a D:/Software/Qt/5.15.2/wasm_32/lib/libQt5EventDispatcherSupport.a D:/Software/Qt/5.15.2/wasm_32/lib/libQt5FontDatabaseSupport.a D:/Software/Qt/5.15.2/wasm_32/lib/libqtfreetype.a D:/Software/Qt/5.15.2/wasm_32/lib/libQt5EglSupport.a D:/Software/Qt/5.15.2/wasm_32/plugins/imageformats/libqgif.a D:/Software/Qt/5.15.2/wasm_32/plugins/imageformats/libqicns.a D:/Software/Qt/5.15.2/wasm_32/plugins/imageformats/libqico.a D:/Software/Qt/5.15.2/wasm_32/plugins/imageformats/libqjpeg.a D:/Software/Qt/5.15.2/wasm_32/plugins/imageformats/libqtga.a D:/Software/Qt/5.15.2/wasm_32/plugins/imageformats/libqtiff.a D:/Software/Qt/5.15.2/wasm_32/plugins/imageformats/libqwbmp.a D:/Software/Qt/5.15.2/wasm_32/plugins/imageformats/libqwebp.a D:/Software/Qt/5.15.2/wasm_32/lib/libQt5Widgets.a D:/Software/Qt/5.15.2/wasm_32/lib/libQt5Gui.a D:/Software/Qt/5.15.2/wasm_32/lib/libqtlibpng.a D:/Software/Qt/5.15.2/wasm_32/lib/libqtharfbuzz.a D:/Software/Qt/5.15.2/wasm_32/lib/libQt5Core.a D:/Software/Qt/5.15.2/wasm_32/lib/libqtpcre2.a   
AR            = emar cqs
RANLIB        = 
SED           = $(QMAKE) -install sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ..\build-76\main.cpp \
		..\build-76\mainwindow.cpp \
		..\build-76\graph_qwidget.cpp E:/jucse/gitRepo/BCSE-III/graphicsLab/build-assignment76-Qt_5_15_2_WebAssembly-Debug/assignment.js_plugin_import.cpp \
		moc_mainwindow.cpp \
		moc_graph_qwidget.cpp
OBJECTS       = main.obj \
		mainwindow.obj \
		graph_qwidget.obj \
		assignment.js_plugin_import.obj \
		moc_mainwindow.obj \
		moc_graph_qwidget.obj
DIST          =  ..\build-76\mainwindow.h \
		..\build-76\graph_qwidget.h ..\build-76\main.cpp \
		..\build-76\mainwindow.cpp \
		..\build-76\graph_qwidget.cpp
QMAKE_TARGET  = assignment.js
DESTDIR       = .\\
TARGET        = .\assignment.js


first: all
####### Build rules

.\assignment.js: D:\Software\Qt\5.15.2\wasm_32\lib\libQt5Widgets.a D:\Software\Qt\5.15.2\wasm_32\lib\libQt5Gui.a D:\Software\Qt\5.15.2\wasm_32\lib\libQt5Core.a ui_mainwindow.h $(OBJECTS)  apphtml appjs appsvg
	@if not exist .\ mkdir .\ & if not exist .\ exit 1
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ..\build-76\assignment76.pro D:\Software\Qt\5.15.2\wasm_32\mkspecs\wasm-emscripten\qmake.conf D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\spec_pre.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\common\sanitize.conf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\common\gcc-base.conf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\common\clang.conf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\qdevice.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\device_config.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\wasm\emcc_ver.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\qconfig.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_bootstrap_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_core.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_core_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_edid_support_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_egl_support_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_fb_support_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_gamepad.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_gamepad_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_gui.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_gui_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_multimedia.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_multimedia_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_network.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_network_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_opengl.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_opengl_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_openglextensions.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_openglextensions_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_printsupport.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_printsupport_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qml.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qml_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qmlmodels.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qmltest.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qmltest_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quick.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quick_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickcontrols2.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickparticles_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickshapes_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quicktemplates2.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickwidgets.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_remoteobjects.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_repparser.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_repparser_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_scxml.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_scxml_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_sensors.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_sensors_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_service_support_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_svg.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_svg_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_testlib.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_testlib_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_texttospeech.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_texttospeech_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_theme_support_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_uiplugin.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_uitools.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_uitools_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_webchannel.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_webchannel_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_websockets.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_websockets_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_webview.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_webview_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_widgets.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_widgets_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_xml.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_xml_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_xmlpatterns.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_zlib_private.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_eglvideonode.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qgif.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qicns.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qico.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qjpeg.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qsvg.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qsvgicon.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtga.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtiff.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtsensors_generic.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qwasm.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qwbmp.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qwebp.pri \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\qt_functions.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\qt_config.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\wasm-emscripten\qmake.conf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\spec_post.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\exclusive_builds.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\toolchain.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\default_pre.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\wasm\default_pre.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\resolve_config.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\default_post.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\qml_debug.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\wasm\wasm.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\warn_on.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\qt.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\resources_functions.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\resources.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\moc.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\unix\opengl.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\uic.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\qmake_use.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\file_copies.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\testcase_targets.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\exceptions.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\yacc.prf \
		D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\lex.prf \
		..\build-76\assignment76.pro \
		D:\Software\Qt\5.15.2\wasm_32\plugins\platforms\libqwasm.prl \
		D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqgif.prl \
		D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqicns.prl \
		D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqico.prl \
		D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqjpeg.prl \
		D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqtga.prl \
		D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqtiff.prl \
		D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqwbmp.prl \
		D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqwebp.prl \
		D:\Software\Qt\5.15.2\wasm_32\lib\libQt5Widgets.prl \
		D:\Software\Qt\5.15.2\wasm_32\lib\libQt5Gui.prl \
		D:\Software\Qt\5.15.2\wasm_32\lib\libQt5Core.prl
	$(QMAKE) -o Makefile ..\build-76\assignment76.pro -spec wasm-emscripten "CONFIG+=debug" "CONFIG+=qml_debug"
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\spec_pre.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\common\sanitize.conf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\common\gcc-base.conf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\common\clang.conf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\qdevice.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\device_config.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\wasm\emcc_ver.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\qconfig.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_accessibility_support_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_core.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_core_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_edid_support_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_egl_support_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_fb_support_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_gamepad.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_gamepad_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_gui.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_gui_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_multimedia.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_network.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_network_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_opengl.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_openglextensions.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_printsupport.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qml.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qml_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qmlmodels.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qmlmodels_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qmltest.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quick.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quick_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickcontrols2.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickshapes_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quicktemplates2.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_remoteobjects.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_remoteobjects_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_repparser.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_repparser_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_scxml.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_scxml_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_sensors.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_sensors_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_service_support_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_svg.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_svg_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_testlib.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_texttospeech.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_texttospeech_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_theme_support_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_uiplugin.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_uitools.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_uitools_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_webchannel.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_webchannel_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_websockets.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_websockets_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_webview.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_webview_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_widgets.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_xml.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_xml_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_lib_zlib_private.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_eglvideonode.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qgif.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qicns.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qico.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qjpeg.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qsvg.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qsvgicon.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtga.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtiff.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtsensors_generic.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qwasm.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qwbmp.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\modules\qt_plugin_qwebp.pri:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\qt_functions.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\qt_config.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\wasm-emscripten\qmake.conf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\spec_post.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\exclusive_builds.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\toolchain.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\default_pre.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\wasm\default_pre.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\resolve_config.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\default_post.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\qml_debug.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\wasm\wasm.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\warn_on.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\qt.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\resources_functions.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\resources.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\moc.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\unix\opengl.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\uic.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\qmake_use.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\file_copies.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\testcase_targets.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\exceptions.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\yacc.prf:
D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\lex.prf:
..\build-76\assignment76.pro:
D:\Software\Qt\5.15.2\wasm_32\plugins\platforms\libqwasm.prl:
D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqgif.prl:
D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqicns.prl:
D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqico.prl:
D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqjpeg.prl:
D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqtga.prl:
D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqtiff.prl:
D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqwbmp.prl:
D:\Software\Qt\5.15.2\wasm_32\plugins\imageformats\libqwebp.prl:
D:\Software\Qt\5.15.2\wasm_32\lib\libQt5Widgets.prl:
D:\Software\Qt\5.15.2\wasm_32\lib\libQt5Gui.prl:
D:\Software\Qt\5.15.2\wasm_32\lib\libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ..\build-76\assignment76.pro -spec wasm-emscripten "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE


all: Makefile .\assignment.js

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`\$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)\
	$(COPY_FILE) --parents D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\data\dummy.cpp $(DISTDIR)\
	$(COPY_FILE) --parents ..\build-76\mainwindow.h ..\build-76\graph_qwidget.h $(DISTDIR)\
	$(COPY_FILE) --parents ..\build-76\main.cpp ..\build-76\mainwindow.cpp ..\build-76\graph_qwidget.cpp $(DISTDIR)\
	$(COPY_FILE) --parents ..\build-76\mainwindow.ui $(DISTDIR)\


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) *.html *.js *.wasm E:/jucse/gitRepo/BCSE-III/graphicsLab/build-assignment76-Qt_5_15_2_WebAssembly-Debug/assignment.js_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

apphtml: D:/Software/Qt/5.15.2/wasm_32/plugins/platforms/wasm_shell.html
	$(QMAKE) -install sed -e s/@APPNAME@/assignment/g D:/Software/Qt/5.15.2/wasm_32/plugins/platforms/wasm_shell.html > E:/jucse/gitRepo/BCSE-III/graphicsLab/build-assignment76-Qt_5_15_2_WebAssembly-Debug/assignment.html

appjs: D:/Software/Qt/5.15.2/wasm_32/plugins/platforms/qtloader.js
	copy /y D:\Software\Qt\5.15.2\wasm_32\plugins\platforms\qtloader.js E:\jucse\gitRepo\BCSE-III\graphicsLab\build-assignment76-Qt_5_15_2_WebAssembly-Debug

appsvg: D:/Software/Qt/5.15.2/wasm_32/plugins/platforms/qtlogo.svg
	copy /y D:\Software\Qt\5.15.2\wasm_32\plugins\platforms\qtlogo.svg E:\jucse\gitRepo\BCSE-III\graphicsLab\build-assignment76-Qt_5_15_2_WebAssembly-Debug

shellfiles: apphtml appjs appsvg

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_apphtml_make_all:
compiler_apphtml_clean:
	-$(DEL_FILE) assignment.html
compiler_appjs_make_all:
compiler_appjs_clean:
	-$(DEL_FILE) qtloader.js
compiler_appsvg_make_all:
compiler_appsvg_clean:
	-$(DEL_FILE) qtlogo.svg
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\data\dummy.cpp
	em++ -g -std=gnu++11 -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra -dM -E -o moc_predefs.h D:\Software\Qt\5.15.2\wasm_32\mkspecs\features\data\dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_graph_qwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_graph_qwidget.cpp
moc_mainwindow.cpp: ..\build-76\mainwindow.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QMainWindow \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qmainwindow.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgetsglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtguiglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig-bootstrapped.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtcore-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsystemdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qprocessordetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcompilerdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtypeinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsysinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlogging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qflags.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbasicatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_bootstrap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qgenericatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_cxx11.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_msvc.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobalstatic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmutex.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnumeric.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qversiontagging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtgui-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgets-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnamespace.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs_win.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstring.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qchar.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrefcount.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qarraydata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringliteral.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringview.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringbuilder.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiterator.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhashfunctions.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpair.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvector.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainertools_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpoint.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearraylist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qregexp.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringmatcher.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcoreevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qscopedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmetatype.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvarlengtharray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainerfwd.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmargins.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpaintdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrect.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsize.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpalette.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcolor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgb.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgba64.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qbrush.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qmatrix.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpolygon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qregion.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdatastream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiodevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qline.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtransform.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qimage.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixelformat.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qshareddata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhash.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfont.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontmetrics.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qsizepolicy.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcursor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qkeysequence.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvariant.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdebug.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtextstream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlocale.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qset.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontiguouscache.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurlquery.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfile.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfiledevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qvector2d.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtouchdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtabwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qicon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QLabel \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qlabel.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qframe.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QVector \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QPair \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmath.h \
		moc_predefs.h \
		D:\Software\Qt\5.15.2\wasm_32\bin\moc.exe
	D:\Software\Qt\5.15.2\wasm_32\bin\moc.exe $(DEFINES) --include E:/jucse/gitRepo/BCSE-III/graphicsLab/build-assignment76-Qt_5_15_2_WebAssembly-Debug/moc_predefs.h -ID:/Software/Qt/5.15.2/wasm_32/mkspecs/wasm-emscripten -IE:/jucse/gitRepo/BCSE-III/graphicsLab/build-76 -ID:/Software/Qt/5.15.2/wasm_32/include -ID:/Software/Qt/5.15.2/wasm_32/include/QtWidgets -ID:/Software/Qt/5.15.2/wasm_32/include/QtGui -ID:/Software/Qt/5.15.2/wasm_32/include/QtCore -I. ..\build-76\mainwindow.h -o moc_mainwindow.cpp

moc_graph_qwidget.cpp: ..\build-76\graph_qwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QWidget \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgetsglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtguiglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig-bootstrapped.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtcore-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsystemdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qprocessordetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcompilerdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtypeinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsysinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlogging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qflags.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbasicatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_bootstrap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qgenericatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_cxx11.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_msvc.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobalstatic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmutex.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnumeric.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qversiontagging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtgui-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgets-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnamespace.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs_win.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstring.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qchar.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrefcount.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qarraydata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringliteral.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringview.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringbuilder.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiterator.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhashfunctions.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpair.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvector.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainertools_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpoint.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearraylist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qregexp.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringmatcher.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcoreevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qscopedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmetatype.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvarlengtharray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainerfwd.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmargins.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpaintdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrect.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsize.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpalette.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcolor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgb.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgba64.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qbrush.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qmatrix.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpolygon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qregion.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdatastream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiodevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qline.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtransform.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qimage.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixelformat.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qshareddata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhash.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfont.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontmetrics.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qsizepolicy.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcursor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qkeysequence.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvariant.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdebug.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtextstream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlocale.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qset.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontiguouscache.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurlquery.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfile.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfiledevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qvector2d.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtouchdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\QMouseEvent \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QEvent \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QDebug \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QStyle \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qstyle.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qicon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\QPainter \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpainter.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtextoption.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpen.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QStyleOption \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qstyleoption.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qabstractspinbox.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qvalidator.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qregularexpression.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qslider.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qabstractslider.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtabbar.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtabwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qrubberband.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qframe.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qabstractitemmodel.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QTime \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdatetime.h \
		moc_predefs.h \
		D:\Software\Qt\5.15.2\wasm_32\bin\moc.exe
	D:\Software\Qt\5.15.2\wasm_32\bin\moc.exe $(DEFINES) --include E:/jucse/gitRepo/BCSE-III/graphicsLab/build-assignment76-Qt_5_15_2_WebAssembly-Debug/moc_predefs.h -ID:/Software/Qt/5.15.2/wasm_32/mkspecs/wasm-emscripten -IE:/jucse/gitRepo/BCSE-III/graphicsLab/build-76 -ID:/Software/Qt/5.15.2/wasm_32/include -ID:/Software/Qt/5.15.2/wasm_32/include/QtWidgets -ID:/Software/Qt/5.15.2/wasm_32/include/QtGui -ID:/Software/Qt/5.15.2/wasm_32/include/QtCore -I. ..\build-76\graph_qwidget.h -o moc_graph_qwidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ..\build-76\mainwindow.ui \
		D:\Software\Qt\5.15.2\wasm_32\bin\uic.exe \
		..\build-76\graph_qwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QWidget \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgetsglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtguiglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig-bootstrapped.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtcore-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsystemdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qprocessordetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcompilerdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtypeinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsysinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlogging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qflags.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbasicatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_bootstrap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qgenericatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_cxx11.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_msvc.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobalstatic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmutex.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnumeric.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qversiontagging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtgui-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgets-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnamespace.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs_win.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstring.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qchar.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrefcount.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qarraydata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringliteral.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringview.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringbuilder.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiterator.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhashfunctions.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpair.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvector.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainertools_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpoint.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearraylist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qregexp.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringmatcher.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcoreevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qscopedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmetatype.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvarlengtharray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainerfwd.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmargins.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpaintdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrect.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsize.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpalette.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcolor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgb.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgba64.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qbrush.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qmatrix.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpolygon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qregion.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdatastream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiodevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qline.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtransform.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qimage.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixelformat.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qshareddata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhash.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfont.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontmetrics.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qsizepolicy.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcursor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qkeysequence.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvariant.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdebug.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtextstream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlocale.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qset.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontiguouscache.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurlquery.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfile.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfiledevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qvector2d.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtouchdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\QMouseEvent \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QEvent \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QDebug \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QStyle \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qstyle.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qicon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\QPainter \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpainter.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtextoption.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpen.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QStyleOption \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qstyleoption.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qabstractspinbox.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qvalidator.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qregularexpression.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qslider.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qabstractslider.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtabbar.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtabwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qrubberband.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qframe.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qabstractitemmodel.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QTime \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdatetime.h
	D:\Software\Qt\5.15.2\wasm_32\bin\uic.exe ..\build-76\mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.obj: ..\build-76\main.cpp ..\build-76\mainwindow.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QMainWindow \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qmainwindow.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgetsglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtguiglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig-bootstrapped.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtcore-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsystemdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qprocessordetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcompilerdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtypeinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsysinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlogging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qflags.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbasicatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_bootstrap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qgenericatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_cxx11.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_msvc.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobalstatic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmutex.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnumeric.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qversiontagging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtgui-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgets-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnamespace.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs_win.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstring.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qchar.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrefcount.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qarraydata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringliteral.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringview.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringbuilder.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiterator.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhashfunctions.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpair.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvector.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainertools_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpoint.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearraylist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qregexp.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringmatcher.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcoreevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qscopedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmetatype.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvarlengtharray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainerfwd.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmargins.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpaintdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrect.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsize.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpalette.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcolor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgb.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgba64.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qbrush.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qmatrix.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpolygon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qregion.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdatastream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiodevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qline.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtransform.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qimage.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixelformat.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qshareddata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhash.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfont.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontmetrics.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qsizepolicy.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcursor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qkeysequence.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvariant.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdebug.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtextstream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlocale.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qset.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontiguouscache.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurlquery.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfile.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfiledevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qvector2d.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtouchdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtabwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qicon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QLabel \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qlabel.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qframe.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QVector \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QPair \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmath.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QApplication \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qapplication.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcoreapplication.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qeventloop.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qdesktopwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qguiapplication.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qinputmethod.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj ..\build-76\main.cpp

mainwindow.obj: ..\build-76\mainwindow.cpp ..\build-76\mainwindow.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QMainWindow \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qmainwindow.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgetsglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtguiglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig-bootstrapped.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtcore-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsystemdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qprocessordetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcompilerdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtypeinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsysinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlogging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qflags.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbasicatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_bootstrap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qgenericatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_cxx11.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_msvc.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobalstatic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmutex.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnumeric.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qversiontagging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtgui-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgets-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnamespace.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs_win.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstring.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qchar.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrefcount.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qarraydata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringliteral.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringview.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringbuilder.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiterator.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhashfunctions.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpair.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvector.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainertools_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpoint.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearraylist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qregexp.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringmatcher.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcoreevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qscopedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmetatype.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvarlengtharray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainerfwd.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmargins.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpaintdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrect.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsize.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpalette.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcolor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgb.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgba64.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qbrush.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qmatrix.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpolygon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qregion.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdatastream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiodevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qline.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtransform.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qimage.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixelformat.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qshareddata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhash.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfont.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontmetrics.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qsizepolicy.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcursor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qkeysequence.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvariant.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdebug.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtextstream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlocale.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qset.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontiguouscache.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurlquery.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfile.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfiledevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qvector2d.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtouchdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtabwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qicon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QLabel \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qlabel.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qframe.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QVector \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QPair \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmath.h \
		ui_mainwindow.h \
		..\build-76\graph_qwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QWidget \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\QMouseEvent \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QEvent \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QDebug \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QStyle \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qstyle.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\QPainter \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpainter.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtextoption.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpen.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QStyleOption \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qstyleoption.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qabstractspinbox.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qvalidator.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qregularexpression.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qslider.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qabstractslider.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtabbar.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qrubberband.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qabstractitemmodel.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QTime \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.obj ..\build-76\mainwindow.cpp

graph_qwidget.obj: ..\build-76\graph_qwidget.cpp ..\build-76\graph_qwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QWidget \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgetsglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtguiglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobal.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig-bootstrapped.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qconfig.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtcore-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsystemdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qprocessordetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcompilerdetection.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtypeinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsysinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlogging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qflags.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbasicatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_bootstrap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qgenericatomic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_cxx11.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qatomic_msvc.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qglobalstatic.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmutex.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnumeric.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qversiontagging.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtgui-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtwidgets-config.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qnamespace.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobjectdefs_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qwindowdefs_win.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstring.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qchar.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrefcount.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qarraydata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringliteral.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringview.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringbuilder.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qalgorithms.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiterator.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhashfunctions.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpair.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvector.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainertools_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qpoint.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qbytearraylist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringlist.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qregexp.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qstringmatcher.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcoreevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qscopedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmetatype.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvarlengtharray.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontainerfwd.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qobject_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmargins.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpaintdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qrect.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsize.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpalette.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcolor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgb.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qrgba64.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qbrush.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qmatrix.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpolygon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qregion.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdatastream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qiodevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qline.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtransform.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qimage.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixelformat.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpixmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qshareddata.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qhash.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qsharedpointer_impl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfont.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontmetrics.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qfontinfo.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qsizepolicy.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qcursor.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qkeysequence.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qevent.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qvariant.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmap.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdebug.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qtextstream.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qlocale.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qset.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qcontiguouscache.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurl.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qurlquery.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfile.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qfiledevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qvector2d.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtouchdevice.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\QMouseEvent \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QEvent \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QDebug \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QStyle \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qstyle.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qicon.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\QPainter \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpainter.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qtextoption.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qpen.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QStyleOption \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qstyleoption.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qabstractspinbox.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtGui\qvalidator.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qregularexpression.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qslider.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qabstractslider.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtabbar.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qtabwidget.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qrubberband.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qframe.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qabstractitemmodel.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QTime \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qdatetime.h \
		..\build-76\mainwindow.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QMainWindow \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qmainwindow.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\QLabel \
		D:\Software\Qt\5.15.2\wasm_32\include\QtWidgets\qlabel.h \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QVector \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\QPair \
		D:\Software\Qt\5.15.2\wasm_32\include\QtCore\qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graph_qwidget.obj ..\build-76\graph_qwidget.cpp

assignment.js_plugin_import.obj: E:/jucse/gitRepo/BCSE-III/graphicsLab/build-assignment76-Qt_5_15_2_WebAssembly-Debug/assignment.js_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o assignment.js_plugin_import.obj E:/jucse/gitRepo/BCSE-III/graphicsLab/build-assignment76-Qt_5_15_2_WebAssembly-Debug/assignment.js_plugin_import.cpp

moc_mainwindow.obj: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.obj moc_mainwindow.cpp

moc_graph_qwidget.obj: moc_graph_qwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graph_qwidget.obj moc_graph_qwidget.cpp

####### Install

install_js_file: first FORCE
	@if not exist E:$(INSTALL_ROOT:@msyshack@%=%)\jucse\gitRepo\BCSE-III\graphicsLab\build-76\. mkdir E:$(INSTALL_ROOT:@msyshack@%=%)\jucse\gitRepo\BCSE-III\graphicsLab\build-76\. & if not exist E:$(INSTALL_ROOT:@msyshack@%=%)\jucse\gitRepo\BCSE-III\graphicsLab\build-76\. exit 1
	$(QINSTALL_PROGRAM) E:\jucse\gitRepo\BCSE-III\graphicsLab\build-76\assignment.js E:$(INSTALL_ROOT:@msyshack@%=%)\jucse\gitRepo\BCSE-III\graphicsLab\build-76\.\assignment.js

uninstall_js_file: FORCE
	-$(DEL_FILE) E:$(INSTALL_ROOT:@msyshack@%=%)\jucse\gitRepo\BCSE-III\graphicsLab\build-76\.\assignment.js
	-$(DEL_DIR) E:$(INSTALL_ROOT:@msyshack@%=%)\jucse\gitRepo\BCSE-III\graphicsLab\build-76\. 


install: install_js_file  FORCE

uninstall: uninstall_js_file  FORCE

FORCE:

